name: Local - Procurement Portal
values:
  - key: baseUrl
    value: 'http://localhost:3000/api'
    enabled: true
  - key: accessToken
    value: ''
    enabled: true
  - key: jwt
    value: ''
    enabled: true
