FROM node:20-alpine AS builder
WORKDIR /workspace

COPY package.json package-lock.json nx.json tsconfig.base.json eslint.config.mjs ./
COPY apps ./apps
COPY shared-types ./shared-types

RUN npm install --no-audit --no-fund
RUN npx nx build procurement-portal

FROM nginx:1.27-alpine AS runner

COPY deploy/nginx/web.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /workspace/dist/apps/procurement-portal/browser /usr/share/nginx/html

EXPOSE 4000
CMD ["nginx", "-g", "daemon off;"]
